### ISSUE TITLE
Invisible Items

### ISSUE THREAD

**Issue by nrllewellyn** [ganymedes01/TheErebus#734]
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Mod Version: 1.0.29

Description:
Items that should be rendered in 3D are invisible in the inventory/JEI. I'm guessing, based on comments here (https://github.com/vadis365/TheErebus/issues/576) that this is a cross-mod compatibility issue with Botania.

**Comment by nrllewellyn** [comment]
Example items: Bamboo shield, Wasp Dagger, Web Slinger, Staff of Geae

**Comment by nrllewellyn** [comment]
(A simple work-around might be to offer 2D sprites for these items and have a config option to turn off 3D rendering, if it's too hard to fix.)

**Comment by vadis365** [comment]
I'm not really sure what is going on here - I mean the mod is in a big pack like PO3 with a tons of mods and it doesn't have the same issue. The bug with Botania was fixed aaaaaaaaaaages ago so it shouldn't be that.
I would suggest you remove whatever mod is causing it - Irc wasn't it Endless Traverse that was actually found to be the culprit in the other issue relating to this? #619

**Comment by CorporalData** [comment]
I don’t have the botania mod installed but the 3d models dont render/are invisible in the inventory and when you hold/equip them. Are there any other mods that are incompatible with The Erebus? If so, please inform me. I will list all the mods that are installed if you want. The items are the ones with 3D models (eg. augmented scorpion claw, shields etc.)

**Comment by ben-mkiv** [comment]
Bug was in OpenSecurity, so this can be closed. (Fixed with OpenSecurity version 1.0-39)

Anyways, we should both rely on `Item#setTileEntityItemStackRenderer` instead of overriding `TileEntityItemStackRenderer.instance`

**Comment by nrllewellyn** [comment]
Issue still exists with OpenSecurity 1.0-39, so OpenSecurity may have not been the only one causing this issue.

**Comment by vadis365** [comment]
fixed as of above merged.
